### ISSUE TITLE
Conversion to Neuron fails when there is no target component

### ISSUE THREAD

**Issue by adrianq** [NeuroML/org.neuroml.export#33]
When we try to convert a model which has no target component it fails throwing the following exception:

[2015-06-17 12:50:09.141] ERROR http-bio-8080-exec-47        System.err                                                        Caused by: org.lemsml.jlems.core.sim.ContentError: No runnable components have been specified 
[2015-06-17 12:50:09.141] ERROR http-bio-8080-exec-47        System.err                                                         at org.lemsml.jlems.core.type.Lems.getTarget(Lems.java:334) 
[2015-06-17 12:50:09.141] ERROR http-bio-8080-exec-47        System.err                                                         at org.neuroml.export.neuron.NeuronWriter.getMainScript(NeuronWriter.java:220)

If we want to convert the model in order to run a simulation this is not a problem as we will always have a target component. However when we just want to convert the model (and maybe download it from Geppetto) this becomes a problem.

@pgleeson Is there any reason why we should have a target component in order to convert a model (TBH I haven't look at the NeuronWriter code in detail)?

**Comment by pgleeson** [comment]
That's the intended behaviour at present. 

Yes, it could be cleverer and see that it's a NML2 model only (not target), but that's not there yet...

**Comment by pgleeson** [comment]
Intended behaviour...
