### ISSUE TITLE
Support for MinGW and newer versions of NEURON?

### ISSUE THREAD

**Issue by clausagerskov** [NeuroML/org.neuroml.export#81]
I am trying to compile an LEMS xml file with NEURON 8.0 installed on Windows 10 and am getting the following error message:

****
  Unfortunately, jNeuroML doesn't currently support MinGW versions of NEURON. Try the Cygwin version of 7.3, e.g. nrn-7.3.i686-pc-cygwin-setup.exe
****

(LOG)   at org.lemsml.jlems.core.logging.E.multiError(E.java:251)
(LOG)   at org.lemsml.jlems.core.logging.E.error(E.java:217)
(LOG)   at org.neuroml.export.neuron.ProcessManager.compileFileWithNeuron(ProcessManager.java:376)
(LOG)   at org.neuroml.export.neuron.NeuronWriter.generateAndRun(NeuronWriter.java:163)
(LOG)   at org.neuroml.JNeuroML.main(JNeuroML.java:517)
org.neuroml.model.util.NeuroMLException: Error testing: C:\Users\claus\source\repos\ow\OpenWorm\output\C2_FW_2022-02-22_18-50-54.
Is NEURON correctly installed?
NEURON home dir being used: C:\nrn

        at org.neuroml.export.neuron.ProcessManager.compileFileWithNeuron(ProcessManager.java:386)
        at org.neuroml.export.neuron.NeuronWriter.generateAndRun(NeuronWriter.java:163)
        at org.neuroml.JNeuroML.main(JNeuroML.java:517)
Caused by: org.neuroml.model.util.NeuroMLException: ****
  Unfortunately, jNeuroML doesn't currently support MinGW versions of NEURON. Try the Cygwin version of 7.3, e.g. nrn-7.3.i686-pc-cygwin-setup.exe
****

        at org.neuroml.export.neuron.ProcessManager.compileFileWithNeuron(ProcessManager.java:152)
        ... 2 more

Is this going to be supported some day?

**Comment by pgleeson** [comment]
See https://github.com/NeuroML/pyNeuroML/issues/67#issuecomment-1059339330. Unfortunately windows support is low priority for us due to lower demand from users of this OS...
