### ISSUE TITLE
Neuron mechanism fails with MacOS .dylib files[Bug]

### ISSUE THREAD

**Issue by christian-oreilly** [NeuroML/org.neuroml.export#85]
In short, the command `java -Xmx2G  -Djava.awt.headless=true -jar  "jNeuroML-0.11.1-jar-with-dependencies.jar"   "LEMS_sim.xml" -neuron -run -compile -nogui -I ''` fails because nrnivmodl generates a file named `libnrnmech.dylib` but neuroml expect a file with an extension .so or .la. The relevant part of the log:

```
 jNeuroML >>  (INFO) NMODL Compile >> >  -> Compiling leak_chan.c
 jNeuroML >>  (INFO) NMODL Compile >> >  -> Compiling pg_olm.c
 jNeuroML >>  (INFO) NMODL Compile >> >  -> Compiling pg_pyr.c
 jNeuroML >>  (INFO) NMODL Compile >> >  => LINKING shared library ./libnrnmech.dylib
 jNeuroML >>  (INFO) NMODL Compile >> >  => LINKING executable ./special LDFLAGS are:    
 jNeuroML >>  (INFO) NMODL Compile >> > Successfully created x86_64/special
 jNeuroML >>  (INFO) Executed command /Users/christian/opt/anaconda3/bin/nrnivmodl
 jNeuroML >>  (INFO) Verifying mod file compilation: looking for file: /Users/christian/gdrive/publications_current/Journal/amygdala_model/i686/libnrnmech.la
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/i686/libnrnmech.la not found.
 jNeuroML >>  (INFO) Verifying mod file compilation: looking for file: /Users/christian/gdrive/publications_current/Journal/amygdala_model/x86_64/libnrnmech.la
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/x86_64/libnrnmech.la not found.
 jNeuroML >>  (INFO) Verifying mod file compilation: looking for file: /Users/christian/gdrive/publications_current/Journal/amygdala_model/i686/libnrnmech.so
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/i686/libnrnmech.so not found.
 jNeuroML >>  (INFO) Verifying mod file compilation: looking for file: /Users/christian/gdrive/publications_current/Journal/amygdala_model/x86_64/libnrnmech.so
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/x86_64/libnrnmech.so not found.
 jNeuroML >>  (INFO) Verifying mod file compilation: looking for file: /Users/christian/gdrive/publications_current/Journal/amygdala_model/i686/libnrnmech.la
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/i686/libnrnmech.la not found.
 jNeuroML >>  (INFO) Verifying mod file compilation: looking for file: /Users/christian/gdrive/publications_current/Journal/amygdala_model/umac/libnrnmech.la
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/umac/libnrnmech.la not found.
 jNeuroML >>  (INFO) Compilation failed. Unable to find necessary file(s). Please note that Neuron checks every *.mod file in this file's parent directory
 jNeuroML >>  (/Users/christian/gdrive/publications_current/Journal/amygdala_model).
 jNeuroML >>  For more information when this error occurs, enable logging at Settings -> General Properties & Project Defaults -> Logging
 jNeuroML >>  
 jNeuroML >>     NOTE: make sure you can compile NEURON mod files on your system!
 jNeuroML >>  
 jNeuroML >>  Often, extra packages (e.g. dev packages of ncurses & readline) need to be installed to successfully run nrnivmodl, which compiles mod files
 jNeuroML >>  Go to /Users/christian/gdrive/publications_current/Journal/amygdala_model and try running nrnivmodl
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/i686/libnrnmech.la
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/x86_64/libnrnmech.la
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/i686/libnrnmech.so
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/x86_64/libnrnmech.so
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/i686/libnrnmech.la
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/umac/libnrnmech.la
 jNeuroML >>  (INFO) Deleting generated dir(s): 
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/i686
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/x86_64
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/i686
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/x86_64
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/i686
 jNeuroML >>  (INFO) /Users/christian/gdrive/publications_current/Journal/amygdala_model/umac
 jNeuroML >>  (INFO) Success in compiling mods: false
 jNeuroML >>  org.neuroml.model.util.NeuroMLException: Error compiling mod files: /Users/christian/gdrive/publications_current/Journal/amygdala_model/leak_chan.mod; /Users/christian/gdrive/publications_current/Journal/amygdala_model/HCNolm.mod; /Users/christian/gdrive/publications_current/Journal/amygdala_model/Kdrfast.mod; /Users/christian/gdrive/publications_current/Journal/amygdala_model/KvAolm.mod; /Users/christian/gdrive/publications_current/Journal/amygdala_model/Nav.mod; /Users/christian/gdrive/publications_current/Journal/amygdala_model/pg_olm.mod; 
 jNeuroML >>  	at org.neuroml.export.neuron.NeuronWriter.generateAndRun(NeuronWriter.java:176)
 jNeuroML >>  	at org.neuroml.JNeuroML.main(JNeuroML.java:517)
 jNeuroML >>  
pyNeuroML >>> ERROR - execute_command_in_dir returned with output:  jNeuroML v0.11.1
```

GCC version:
```
% gcc -v      
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
```

NEURON -- VERSION 8.2.1 HEAD (c1590692) 2022-08-09

This problems comes up for example when using `pynml.run_lems_with_jneuroml_neuron(...)`.

**Comment by christian-oreilly** [comment]
Note that I can run `pynml.run_lems_with_jneuroml_neuron(...)` which generates the .mod before crashing. Then I can run `nrnivmodl` and

```
import shutil
shutil.copy("x86_64/libnrnmech.dylib", "x86_64/libnrnmech.so")
```

and then call again  `pynml.run_lems_with_jneuroml_neuron(...)` and it works fine. So, looks to me like you would just need to add the "dylib" extension in the files checked around https://github.com/NeuroML/org.neuroml.export/blob/ce18e86d14b523c3c28a2d3604cd18325ccb4b29/src/main/java/org/neuroml/export/neuron/ProcessManager.java#L178-L220

**Comment by sanjayankur31** [comment]
Thanks @christian-oreilly , I've opened PR #86 to fix this.

**Comment by christian-oreilly** [comment]
Thanks, @sanjayankur31

**Comment by christian-oreilly** [comment]
Sorry, I hit the button by mistake.

**Comment by pgleeson** [comment]
@christian-oreilly Please try with the latest version of pyNeuroML: https://pypi.org/project/pyNeuroML/#history to see if this issue is fixed for you.
