### ISSUE TITLE
Improve path related errors to help users figure out what is wrong with their paths

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/org.neuroml.export#98]
At the moment, while trying to get the correct path to record from a synapse, the errors are not very helpful to users. They're of this form:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.lemsml.jlems.core.type.Component.getComponentType()" because "c" is null
        at org.neuroml.export.neuron.LEMSQuantityPathNeuron.getExposure(LEMSQuantityPathNeuron.java:91)
        at org.neuroml.export.neuron.LEMSQuantityPathNeuron.getExposure(LEMSQuantityPathNeuron.java:117)
        at org.neuroml.export.neuron.LEMSQuantityPathNeuron.getDimension(LEMSQuantityPathNeuron.java:151)
        at org.neuroml.export.neuron.NeuronWriter.getMainScript(NeuronWriter.java:1415)
        at org.neuroml.export.neuron.NeuronWriter.generateMainScriptAndMods(NeuronWriter.java:288)
        at org.neuroml.export.neuron.NeuronWriter.generateAndRun(NeuronWriter.java:156)
        at org.neuroml.JNeuroML.main(JNeuroML.java:525)
```

I wonder if it is possible for us to print some more information, for example---what `component` was it trying to get the `componentType` of? That'll help users figure out where the error is in the path.

**Comment by borismarin** [comment]
@sanjayankur31 could you please provide a test case?
